package fr.fresnel.fourPolar.core.image.captured;

import fr.fresnel.fourPolar.core.image.captured.file.ICapturedImageFile;
import fr.fresnel.fourPolar.core.image.generic.Image;
import fr.fresnel.fourPolar.core.image.generic.pixel.types.UINT16;
import fr.fresnel.fourPolar.core.imagingSetup.imageFormation.Cameras;

/**
 * A captured image is a single microscopic image file given by the user. This
 * single image may have one or several channels inside, and one, two or four
 * polarizations.
 */
public interface ICapturedImage {
    /**
     * Returns the captured file set corresponding to this image.
     * 
     * @return
     */
    public ICapturedImageFile getCapturedImageFile();

    /**
     * Returns the label of this image in the captured file set. This the same label as
     * those generated by {@link Cameras}.
     * 
     * @return
     */
    public String getLabel();

    /**
     * Get the actual image as a UINT16 image.
     * 
     * @return
     */
    public Image<UINT16> getImage();

    /**
     * Returns the channels associatd with this captured image.
     */
    public int[] channels();

}